services:
  portfolio:
    build:
      context: .
      args:
        LOCALE de_DE
    container_name: portfolio
    restart: unless-stopped
    ports:
      - 5800:5800
    volumes:
      - ./workspace:/opt/portfolio/workspace
    environment:
      KEEP_APP_RUNNING: 1
      USER_ID: 0
      GROUP_ID: 0
      TZ: Europe/Berlin
